name: 'ZAP API Scan'
description: 'Scans the web application with the ZAP API Scan'
branding:
  icon: 'zap'
  color: 'blue'
inputs:
  token:
    description: 'GitHub Token to create issues in the repository'
    required: false
    default: ${{ github.token }}
  target:
    description: 'Target URL'
    required: true
  html_report_name: 
    description: 'Name of the html report file'
    required: false
    default: 'report_html.html'
  json_report_name:
    description: 'Name of the json report file'
    required: false
    default: 'report_json.json'
  md_report_name:
    description: 'Name of the markdown report file'
    required: false
    default: 'report_md.md'
  format:
    description: 'Format openapi, soap or graphql'
    required: false
    default: openapi
  rules_file_name:
    description: 'Relative path of the ZAP configuration file'
    required: false
  docker_name:
    description: 'The Docker file to be executed'
    required: true
    default: 'ghcr.io/zaproxy/zaproxy:stable'
  cmd_options:
    description: 'Additional command line options'
    required: false
  issue_title:
    description: 'The title for the GitHub issue to be created'
    required: false
    default: 'ZAP API Scan Report'
  fail_action:
    description: 'The action status will be set to fail if ZAP identifies any alerts during the api scan'
    required: false
    default: false
  allow_issue_writing:
    description: 'The action will file the report to the GitHub issue using the issue_title input'
    required: false
    default: true
  artifact_name:
    description: 'The name of the artifact that contains the ZAP reports'
    required: false
    default: 'zap_scan'
runs:
  using: 'node20'
  main: 'dist/index.js'
